version: '3.4'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  webinar.dynamo.consoleapp:
    image: ${DOCKER_REGISTRY-}webinardynamoconsoleapp
    build:
      context: .
      dockerfile: Webinar.Dynamo.ConsoleApp/Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: 'oqg5g'
      AWS_SECRET_ACCESS_KEY: 'kpr7j6'
      AWS_DEFAULT_REGION: 'eu-west-1'
      AWS_REGION: 'eu-west-1'
    depends_on:
      - dynamodb-local
  app-node:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: app-node
    ports:
     - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region us-west-2
  webinar.dynamo.locationsapi:
    image: ${DOCKER_REGISTRY-}webinardynamolocationsapi
    build:
      context: .
      dockerfile: Webinar.Dynamo.LocationsApi/Dockerfile

